# Steps to set up a new docker-compose machine:
#
# docker-compose run django ./manage.py migrate
# docker-compose run django ./manage.py createsuperuser
# docker-compose up


version: '3'

volumes:
  node_modules:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    links: 
      - "django"
    volumes:
      - ./etc/nginx/oddslingers-docker-compose.conf:/etc/nginx/nginx.conf
      - ./data/certs:/opt/oddslingers.poker/data/certs
      - ./core:/opt/oddslingers.poker/core

  postgres:
    image: postgres:12-alpine
    env_file:
      - .env
      - .secrets.env
    expose:
      - 5432
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    entrypoint: redis-server --appendonly yes
    expose:
      - 6379
    volumes:
      - ./data/redis:/data

  django:
    build: .
    image: oddslingers:django_base
    env_file:
      - .env
    working_dir: /opt/oddslingers.poker/core/
    command: ./manage.py runserver --http_timeout 120 0.0.0.0:8000 
    stdin_open: true
    tty: true
    depends_on: 
      - postgres
      - redis
    environment:
      ODDSLINGERS_ENV: DEV
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      IS_DOCKER: 1
    env_file:
      - .env
      - .secrets.env
    expose: 
      - 8000
    volumes:
      - ./data:/opt/oddslingers.poker/data
      - ./core:/opt/oddslingers.poker/core
      - ./bin:/opt/oddslingers.poker/bin

  webpack:
    #image: node:8-alpine
    build:
      context: . 
      dockerfile: ./Dockerfile.webpack
    image: oddslingers:webpack
    command: sh -c "(webpack --mode development --watch --info-verbosity verbose & node-sass-chokidar --watch scss/ -o ../static/css 2>&1  &)| cat"
    stdin_open: true
    tty: true
    environment:
      ODDSLINGERS_ENV: DEV
    volumes:
      - ./core/js:/opt/oddslingers.poker/core/js
      - ./core/static:/opt/oddslingers.poker/core/static
      # Hide local node_modules
      - ./core/js/node_modules:/src/node_modules
      # Add dumps for UI tests
      - ./core/dumps:/opt/oddslingers.poker/core/dumps


  dramatiq:
    image: oddslingers:django_base
    working_dir: /opt/oddslingers.poker/core/
    command: nice -15 ./manage.py rundramatiq --processes 1 --threads 1
    environment:
      ODDSLINGERS_ENV: DEV
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    cap_add:
      - SYS_NICE
    depends_on: 
      - redis
      - postgres
    env_file:
      - .env
      - .secrets.env
    volumes:
      - ./data:/opt/oddslingers.poker/data
      - ./core:/opt/oddslingers.poker/core
      - ./bin:/opt/oddslingers.poker/bin
 
      #TODO: Fish script sourcing
  yacron:
    image: oddslingers:django_base
    command: yacron -c /opt/oddslingers.poker/etc/yacron/oddslingers-dev.yaml
    environment:
      ODDSLINGERS_ENV: DEV
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      IS_DOCKER: 1
    depends_on: 
      - redis
      - postgres
    env_file:
      - .env
      - .secrets.env
    volumes:
      - ./etc:/opt/oddslingers.poker/etc
      - ./data:/opt/oddslingers.poker/data
      - ./core:/opt/oddslingers.poker/core
      - ./etc/yacron:/opt/oddslingers.poker/etc/yacron
      - ./bin:/opt/oddslingers.poker/bin
